# Generated by Django 4.2.6 on 2023-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0003_infoproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
