# Generated by Django 4.2.6 on 2023-10-26 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0005_historique_alter_infoproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 19, 36, 43219)),
        ),
    ]
