# Generated by Django 4.2.6 on 2023-10-27 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0006_historique_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 10, 55, 48, 218994)),
        ),
    ]
